---
title: "Juno_Analysis"
author: "Steven Turnbull"
date: "20 April 2018"
output: html_document
---
This notebook will take data from the Juno surveys (2016 and 2018) and compare them.

A - embedded
B - adopted
C - developing
D - compliant
E - not in place

First import the data from csv. 
Values are percentages.

```{R}
juno_survey <- read.csv(file = "JunoSurvey.csv", header = TRUE, stringsAsFactors = FALSE)

head(juno_survey)
```

Gather data so multiple rows per question (one for each year question was asked)

```{R}
library(tidyverse)
library(stringr)
#get rid of the X that appears in year
names(juno_survey) <- lapply(names(juno_survey), gsub, pattern='X', replacement='')

#Long format - for plotting
juno_survey_long <- juno_survey %>% gather(key, value, -c(1,2)) %>%
  separate(key, c("Year", "Answer"), sep="_")


juno_survey_long

```

Analysis

```{R}
vars <- c("A","B","C","D","E") # choose Answer columns
vars <- setNames(vars, paste0(vars, "_diff")) # create new column names for difference between years
juno_survey_long %>% group_by(Question_Code, Answer) %>% mutate(diff = value - lag(value)) -> juno_survey_long

juno_survey_long %>% arrange(Question_Code)
```

plot all questions.
This will just show the distributions of answers for each year.
```{R}
juno_survey_long %>%
  ggplot(aes(x=Answer, y=value, color = Year, group = Year)) + geom_line(size=.5) +
    geom_ribbon(aes(x=Answer,ymax=value, fill = Year),ymin=0,alpha=0.3) +
    facet_wrap(~Question_Code) + 
    theme_minimal() 
```

Break it down for each Principle.

Principle 1: A robust organisational framework to deliver equality of opportunity and
reward.

- 1.1 Establish an organisational framework:

```{R}
diff_plot <- function(df, string){df <- df %>%
  filter(str_detect(Question_Code, string)) 
  g <- ggplot(df, aes(x=Answer, y=value, color = Year, group = Year)) + geom_line(size=.5) +
    geom_ribbon(data=df,aes(x=Answer,ymax=value, fill = Year),ymin=0,alpha=0.3) +
    facet_wrap(~Question_Code) + 
    theme_minimal()
  print(g)
  print(paste(unique(df$Question_Code), ": ", unique(df$Question)))}
  
diff_plot(juno_survey_long, "Q..*\\(1.1.*")
```
- 1.2 Monitoring and evidence base:

```{R}
diff_plot(juno_survey_long, "Q..*\\(1.2.*")
```

Principle 2: Appointment and selection processes and procedures that encourage men and
women to apply for academic posts at all levels

2.1 Ensure that processes and procedures are fully inclusive.
```{R}
diff_plot(juno_survey_long, "Q..*\\(2.1.*")
```
2.2 Take positive action to encourage under-represented groups to apply for jobs.
```{R}
diff_plot(juno_survey_long, "Q..*\\(2.2.*")
```

Principle 3: Departmental structures and systems that support and encourage the career
progression and promotion of all staff and enable men and women to progress and continue
in their careers.

3.1 Transparent appraisal and development.
```{R}
diff_plot(juno_survey_long, "Q..*\\(3.1.*")

```

3.2 Transparent promotions processes and procedures
```{R}
diff_plot(juno_survey_long, "Q..*\\(3.2.*")
```

Principle 4: Departmental organisation, structure, management arrangements, and culture
that are open, inclusive and transparent and encourage the participation of all staff

4.1 Promote an inclusive culture
```{R}
diff_plot(juno_survey_long, "Q..*\\(4.1.*")
```

4.2 Transparent workload allocation model
```{R}
diff_plot(juno_survey_long, "Q..*\\(4.2.*")
```


Principle 5: Flexible approaches and provisions that enable individuals, at all career and life
stages, to optimise their contribution to the department, their institution and to STEM.

5.1 Support and promote flexible working practices
```{R}
diff_plot(juno_survey_long, "Q..*\\(5.1.*")
```
